### ISSUE TITLE
Should the completions plugin be enhanced to include more zstyles?

### ISSUE THREAD

**Issue by mattmc3** [belak/zsh-utils#7]
I've spent entirely too much time looking at the zstyle completions available in other projects and cherry picking them into my own config. I'm no completions expert - in fact, completions still feel like a dark art to me (despite pouring over the docs and [how-to](https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org)).

I think robust completions and are a big reason why people stick with the big frameworks (OMZ and Prezto). It's just not something anyone but the most advanced Zsh users seem to grok, but everyone notices and benefits from having good defaults. Which brings me to my point - zsh-utils only includes 2 completion zstyles. Should it include more?

```zsh
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path "$_zcompcache"
```

I'm wondering if it makes sense to borrow from other mature projects. For example, both [Grml-zshrc](https://github.com/grml/grml-etc-core/blob/71bdc48d190a5369fff28a97c828db7b1edf10a9/etc/zsh/zshrc#L750) and [Prezto](https://github.com/sorin-ionescu/prezto/blob/5928fa84cc3b4c711aea5af8bcdddb84e734c54c/modules/completion/init.zsh#L71) have variations on the following settings:

```zsh
zstyle ':completion:*:default'         list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:history-words'   list false
zstyle ':completion:*:history-words'   menu yes
zstyle ':completion:*:history-words'   remove-all-dups yes
zstyle ':completion:*:history-words'   stop yes
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:manuals.(^1*)' insert-sections true
```

Maybe there's some reasoning here I don't know about why zsh-utlis has an anemic completions plugin, so I wanted to start a convo about so I can get a sense for the project goals and completions philosophy prior to submitting a PR.

## References:
* Grml zshrc:

```zsh
$  grep ':completion:' ~/code/github.com/grml/grml-etc-core/etc/zsh/zshrc
    zstyle -a ':grml:completion:compinit' arguments tmp
    zstyle ':completion:*:approximate:'    max-errors 'reply=( $((($#PREFIX+$#SUFFIX)/3 )) numeric )'
    zstyle ':completion:*:complete:-command-::commands' ignored-patterns '(aptitude-*|*\~)'
    zstyle ':completion:*:correct:*'       insert-unambiguous true
    zstyle ':completion:*:corrections'     format $'%{\e[0;31m%}%d (errors: %e)%{\e[0m%}'
    zstyle ':completion:*:correct:*'       original true
    zstyle ':completion:*:default'         list-colors ${(s.:.)LS_COLORS}
    zstyle ':completion:*:descriptions'    format $'%{\e[0;31m%}completing %B%d%b%{\e[0m%}'
    # zstyle ':completion:*:*:cd:*:directory-stack' menu yes select
    zstyle ':completion:*:expand:*'        tag-order all-expansions
    zstyle ':completion:*:history-words'   list false
    zstyle ':completion:*:history-words'   menu yes
    zstyle ':completion:*:history-words'   remove-all-dups yes
    zstyle ':completion:*:history-words'   stop yes
    zstyle ':completion:*'                 matcher-list 'm:{a-z}={A-Z}'
    zstyle ':completion:*:matches'         group 'yes'
    zstyle ':completion:*'                 group-name ''
        zstyle ':completion:*'               menu select=5
    zstyle ':completion:*:messages'        format '%d'
    zstyle ':completion:*:options'         auto-description '%d'
    zstyle ':completion:*:options'         description 'yes'
    zstyle ':completion:*:processes'       command 'ps -au$USER'
    zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters
    zstyle ':completion:*'                 verbose true
    zstyle ':completion:*:-command-:*:'    verbose false
    zstyle ':completion:*:warnings'        format $'%{\e[0;31m%}No matches for:%{\e[0m%} %d'
    zstyle ':completion:*:*:zcompile:*'    ignored-patterns '(*~|*.zwc)'
    zstyle ':completion:correct:'          prompt 'correct to: %e'
    zstyle ':completion::(^approximate*):*:functions' ignored-patterns '_*'
    zstyle ':completion:*:processes-names' command 'ps c -u ${USER} -o command | uniq'
    zstyle ':completion:*:manuals'    separate-sections true
    zstyle ':completion:*:manuals.*'  insert-sections   true
    zstyle ':completion:*:man:*'      menu yes select
    zstyle ':completion:*:sudo:*' command-path /usr/local/sbin \
    zstyle ':completion:*' special-dirs ..
        zstyle ':completion:*' completer _oldlist _expand _force_rehash _complete _files _ignored
        zstyle -e ':completion:*' completer '
    zstyle ':completion:*:urls' local 'www' '/var/www/' 'public_html'
        zstyle ':completion:*' use-cache  yes
        zstyle ':completion:*:complete:*' cache-path "${GRML_COMP_CACHE_DIR}"
    zstyle ':completion:*:hosts' hosts $hosts
zstyle ':completion:hist-complete:*' completer _history
```

* Oh-My-Zsh:
```zsh
$ grep ':completion:' ~/code/github.com/ohmyzsh/ohmyzsh/lib/completion.zsh
zstyle ':completion:*:*:*:*:*' menu select
  zstyle ':completion:*' matcher-list 'r:|=*' 'l:|=* r:|=*'
    zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;34=0=01'
  zstyle ':completion:*:*:*:*:processes' command "ps -u $USERNAME -o pid,user,comm"
  zstyle ':completion:*:*:*:*:processes' command "ps -u $USERNAME -o pid,user,comm -w -w"
zstyle ':completion:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' cache-path $ZSH_CACHE_DIR
zstyle ':completion:*:*:*:users' ignored-patterns \
```

Prezto:

```zsh
$ grep ':completion:' ~/code/github.com/sorin-ionescu/prezto/modules/completion/init.zsh
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*:default' list-prompt '%S%M matches%s'
zstyle ':completion::complete:*' use-cache on
zstyle ':completion::complete:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache}/prezto/zcompcache"
if zstyle -t ':prezto:module:completion:*' case-sensitive; then
  zstyle ':completion:*' matcher-list 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
  zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*:matches' group 'yes'
zstyle ':completion:*:options' description 'yes'
zstyle ':completion:*:options' auto-description '%d'
zstyle ':completion:*:corrections' format ' %F{green}-- %d (errors: %e) --%f'
zstyle ':completion:*:descriptions' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*' format ' %F{yellow}-- %d --%f'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric
zstyle -e ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3>7?7:($#PREFIX+$#SUFFIX)/3))numeric)'
zstyle ':completion:*:functions' ignored-patterns '(_*|pre(cmd|exec))'
zstyle ':completion:*:*:-subscript-:*' tag-order indexes parameters
zstyle ':completion:*:*:cd:*' tag-order local-directories directory-stack path-directories
zstyle ':completion:*:*:cd:*:directory-stack' menu yes select
zstyle ':completion:*:-tilde-:*' group-order 'named-directories' 'path-directories' 'users' 'expand'
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes
zstyle ':completion::*:(-command-|export):*' fake-parameters ${${${_comps[(I)-value-*]#*,}%%,*}:#-*-}
zstyle -a ':prezto:module:completion:*:hosts' etc-host-ignores '_etc_host_ignores'
zstyle -e ':completion:*:hosts' hosts 'reply=(
zstyle ':completion:*:*:*:users' ignored-patterns \
zstyle ':completion:*:(rm|kill|diff):*' ignore-line other
zstyle ':completion:*:rm:*' file-patterns '*:all-files'
zstyle ':completion:*:*:*:*:processes' command 'ps -u $LOGNAME -o pid,user,command -w'
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#) ([0-9a-z-]#)*=01;36=0=01'
zstyle ':completion:*:*:kill:*' menu yes select
zstyle ':completion:*:*:kill:*' force-list always
zstyle ':completion:*:*:kill:*' insert-ids single
zstyle ':completion:*:manuals' separate-sections true
zstyle ':completion:*:manuals.(^1*)' insert-sections true
zstyle ':completion:*:*:mpg123:*' file-patterns '*.(mp3|MP3):mp3\ files *(-/):directories'
zstyle ':completion:*:*:mpg321:*' file-patterns '*.(mp3|MP3):mp3\ files *(-/):directories'
zstyle ':completion:*:*:ogg123:*' file-patterns '*.(ogg|OGG|flac):ogg\ files *(-/):directories'
zstyle ':completion:*:*:mocp:*' file-patterns '*.(wav|WAV|mp3|MP3|ogg|OGG|flac):ogg\ files *(-/):directories'
  zstyle ':completion:*:*:mutt:*' menu yes select
  zstyle ':completion:*:mutt:*' users ${${${(f)"$(<"$HOME/.mutt/aliases")"}#alias[[:space:]]}%%[[:space:]]*}
zstyle ':completion:*:(ssh|scp|rsync):*' tag-order 'hosts:-host:host hosts:-domain:domain hosts:-ipaddr:ip\ address *'
zstyle ':completion:*:(scp|rsync):*' group-order users files all-files hosts-domain hosts-host hosts-ipaddr
zstyle ':completion:*:ssh:*' group-order users hosts-domain hosts-host users hosts-ipaddr
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-host' ignored-patterns '*(.|:)*' loopback ip6-loopback localhost ip6-localhost broadcasthost
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-domain' ignored-patterns '<->.<->.<->.<->' '^[-[:alnum:]]##(.[-[:alnum:]]##)##' '*@*'
zstyle ':completion:*:(ssh|scp|rsync):*:hosts-ipaddr' ignored-patterns '^(<->.<->.<->.<->|(|::)([[:xdigit:].]##:(#c,2))##(|%*))' '127.0.0.<->' '255.255.255.255' '::1' 'fe80::*'
```

**Comment by mattmc3** [comment]
@belak - I hope you aren't getting too sick of me pinging you on this project today with PRs and such. I really appreciate the quick responses and dialog - esp on a project that seems pretty stable and hasn't needed much in the way of contributions for a couple years prior to me shaking things up. Thanks for letting me do that!

Anyway, you got me interested in this project earlier this year with [this comment](https://github.com/sorin-ionescu/prezto/issues/1986#issuecomment-1041241655), and I forked it and added all these enhancements and plugins I thought it needed (to be more like Fish/Prezto/all-the-things) and then slowly realized that what you have here originally was really elegant and I didn't need all that, so I pared down my customizations and ended up back at zsh-utils with basically 5 enhancements:

* support XDG basedirs (#4)
* highlight some Zsh built-ins like run-help (#5)
* add some performance enhancements (#6)
* better completions (#7 this issue)
* One more plugin for color settings (similar to Prezto's spectrum module)

All today's activity has been about giving those enhancements that had staying power back upstream. I really appreciate what you've done here with this project, and this issue and the PRs I opened today represent a pretty robust use of this project for 6 months. Thank you for putting this simple but powerful config out there, especially as other projects like Prezto are really showing their age.

**Comment by belak** [comment]
Thanks for the kind words! I've honestly been in a bit of a rut lately and had to deal with some nonsense in some of the other projects I work on, so it's nice to get a little bit of positive reinforcement every once in a while - it doesn't happen often enough in the open source community, so thank-you. Honestly, I didn't know anyone was using this project other than me!

You're encouraged to submit issues for anything - it helps me know what direction to go as well. PRs are also welcome, but I can't promise I'll accept all of them, especially because I'm aiming to keep this project small-ish and focused. I will always try to take a look though - I really value contributions, especially ones as well thought out as yours.

I would be open to adding better completion settings to this project - my main reason for not including them is that I never had the time to go through the docs and get it how I like - as you mentioned above they're fairly obtuse. The other reason was that my original thought was that this project would be a building block for other ones, but it seems like it works better as a building block for personal configs so some opinionated settings would probably be good. My one request would be an option to disable the more opinionated settings (or maybe a way to switch between different completion styles like themes, but that might be a "later" problem).

**Comment by mattmc3** [comment]
> had to deal with some nonsense in some of the other projects I work on

Heard. Dev life can get like that too fast and too often. It's good to get a reminder of the fun parts now and then. Glad I could do that!

> PRs are also welcome, but I can't promise I'll accept all of them

No expectation of that. While I like the idea that this project can grow and others start to to use it, having a small, tight base config means this project can't be everything to everyone. That's is a goal I can get onboard with and forks are a alternative too if others need something else.

Okay, back to the issue at hand - completions.

> as you mentioned above they're fairly obtuse

Yeah, I'd probably need to document the hell out of each zstyle in the README because of how obtuse they are. Would you be open to an orphan "resources" branch so we could store screenshots?

>  My one request would be an option to disable the more opinionated settings (or maybe a way to switch between different completion styles like themes, but that might be a "later" problem).

I was originally thinking we'd just have a bunch of zstyles that could be customized by the user by either:
* Writing their own zstyles to overwrite ones they don't like
* -OR-
* not using the completions plugin at all, and cherry pick from it whatever they want into their own config

But, your comment about disabling opinionated settings and making it like themes is really clever, and got me thinking there is whole different way to do this.

What if the completions plugin worked like the Zsh prompts? Similar to the built-in `promptinit`, we'd define a `compstyleinit`. Then, similar to the `prompt_belak_setup` function, we'd have `compstyle_belak_setup` (and potentially `compstyle_prezto_setup`, `compstyle_grml_setup`, etc, functions). Users could add their own compstyle function to `$fpath`.

We could then have a `compstyle` command similar to the built-in Zsh `prompt` one that lets you list (`-l`) the compstyles in `$fpath` and switch them to whatever you want. This would keep things light-weight, offer something innovate and fresh that hasn't been done before in the Zsh space, and give users a good set of defaults they can easily swap out.

Talk me out of it. This seems do-able without too much bloat, but it's definitely not as simple as just adding a few `zstyles` to the completion.plugin.zsh file with an `if` block for disabling them. I could always float something out there if you aren't against it and we can collaborate on whether it works as an idea. But I definitely don't want to go down this path if you're against it because it will take a bit of work to assemble a working PR. Think on it and let me know.

**Comment by belak** [comment]
> Talk me out of it.

Haha, no, I won't talk you out of it! I love this idea - it's what I had in mind for the "later" solution I mentioned, but it's only later because I don't have the time to do it at the moment.

Having `compstyle` would allow the base plugin to stay fairly lean, while still making it easy for a user to get a fully-featured completion setup, which solves pretty much all my requirements.

Loading functions from the fpath is fairly easy to do as well, so compstyle wouldn't have to be very complicated. I'd even say for an initial version, we can even assume the user will restart their shell when they're playing with compstyle changes, so we don't need to reset anything like with prompts. Heck, most prompts don't even properly clean up after themselves (and there's not really a way for them to which works consistently).

> Would you be open to an orphan "resources" branch so we could store screenshots?

Maybe? I'm not sure I see the value of it right now, but I could be convinced. Even a folder for screenshots/images would probably be enough, unless there are going to be a ton of them.

**Comment by mattmc3** [comment]
Incoming PR ^

**Comment by mattmc3** [comment]
Now that the PR is merged, I think we can close this issue.

If there are other wish-list features that you had for this project, please feel free to tag me in an issue. I'm happy to pitch in. I've been driving a lot of the features I wanted to see recently, but I'm really interested to know if there's anything you've been thinking about adding but haven't had the time. Of course, the beauty of zsh-utils is that it's not something big and unwieldy like Prezto, so it may be pretty much feature complete in your estimation and that's okay too. Let me know.
